In [1]:
import tensorflow as tf

**张量（Tensor）**：多维数组（列表）
**阶**：张量的维数

维数 | 阶 | 名字 | 例子
-----|----|------|-----
0-D  |0  | 标量 scalar | s=1 2 3 
1-D  |1  | 向量 vector | v=[1, 2, 3]
2-D  |2  | 矩阵 matrix | m=[[1, 2, 3], [4, 5, 6]]
n-D  |n  | 张量 tensor | t=[[[ ... (n 个)

张量可以表示 0 阶到 n 阶数组（列表）

## 1.1 数据类型

 + 整型：`tf.int8`、`tf.int16`、`tf.int32`、`tf.int64`
  - 表示形式：`tf.constant(123, dtype=tf.int32)`
 + 浮点型：`tf.float16`、`tf.float32`、`tf.float64`
  - 表示形式：`tf.constant(3.14, dtype=tf.float32)`
 + 布尔型: `tf.bool`
  - 表示形式：`tf.constant([True, False])`
 + 字符串型：`tf.string`
  - 表示形式：`tf.constant("Hello, World!")`

## 1.2 如何创建一个 Tensor？

`tf.constant(张量内容, dtype=数据类型(可选))`

In [2]:
a = tf.constant([1, 5], dtype=tf.int32)
a # 输出张量的所有信息

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 5])>

In [3]:
a.shape # 张量的形状

TensorShape([2])

In [4]:
a.dtype # 张量的数据类型

tf.int32

### 1.2.1 将 numpy 的数据类型转换为 Tensor 数据类型

`tf.convert_to_tensor(数据名, dtype=数据类型(可选))`

In [5]:
import numpy as np

In [6]:
a = np.arange(0, 5)
a

array([0, 1, 2, 3, 4])

In [7]:
b = tf.convert_to_tensor(a, dtype=tf.int64)
b

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 1, 2, 3, 4], dtype=int64)>

### 1.2.2 创建全为 0 的张量

`tf.zeros(维度)`

In [8]:
tf.zeros([3, 2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

### 1.2.3 创建全为 1 的张量

`tf.ones(维度)`

In [9]:
tf.ones(4)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>

### 1.2.4 创建全为指定值的张量

`tf.fill(维度, 指定值)`

In [10]:
tf.fill([2, 3, 4], 9)

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])>

### 1.2.5 生成正态分布的随机数，默认均值为 0 ，标准差为 1

`tf.random.normal(维度, mean=均值, stddev=标准差)`

In [11]:
tf.random.normal([2, 2], mean=0.5, stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.8740597,  0.6847734],
       [-1.1053822, -1.0417262]], dtype=float32)>


### 1.2.6 生成截断式正态分布的随机数

`tf.random.truncated_normal(维度, mean=均值, stddev=标准差)`

在 `tf.random.truncated_normal` 中如果随机生成数据的取值在 $$(\mu - 2\sigma, \mu + 2\sigma)$$ 之外则重新生成，保证了生成值在均值附近（μ：均值，σ：标准差）。

标准差公式 $$\sigma = \sqrt{\frac{\sum_{i=1}^{n}(x_i - \bar{x})}{n}}$$

In [12]:
tf.random.truncated_normal([2, 2], mean=0.5, stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.59056664, 0.93775856],
       [1.5254349 , 1.3600593 ]], dtype=float32)>

### 实践：梯度下降法求损失函数最小值

梯度下降公式

$$w_{t+1} = w_t - lr * \frac{\partial loss}{\partial w_t}$$

损失函数定义 $$loss = ( w + 1) ^ 2$$

损失函数的导数 $$\frac {\partial loss} {\partial w} = 2w + 2$$

参数 `w` 初始化为 5， 学习率 `lr` 为 0.1， 迭代次数 `epoch` 为 50

In [13]:
w = tf.Variable(5, dtype=tf.float32)
lr = 0.1
epoch = 50

In [14]:
# 开始迭代，次数为 50
for i in range(epoch):
    # 使用 tf.GradientTape 进行梯度计算，下一部分会讲解
    with tf.GradientTape() as tape:
        # 定义损失函数
        loss = tf.square(w + tf.constant(1, dtype=tf.float32))
    # 对损失函数中的参数 w 进行求导
    grads = tape.gradient(loss, w)
    
    # 依据梯度下降公式对参数进行更新，assign_sub 为自减函数，下一部分会讲解
    # w -= lr * grad
    w.assign_sub(lr * grads)
    print('After {} epoch, w is {}, loss is {}'.format(i, w.value(), loss))

After 0 epoch, w is 3.799999952316284, loss is 36.0
After 1 epoch, w is 2.8399999141693115, loss is 23.040000915527344
After 2 epoch, w is 2.072000026702881, loss is 14.745599746704102
After 3 epoch, w is 1.4575999975204468, loss is 9.43718433380127
After 4 epoch, w is 0.9660799503326416, loss is 6.039798259735107
After 5 epoch, w is 0.5728639364242554, loss is 3.8654704093933105
After 6 epoch, w is 0.2582911550998688, loss is 2.4739010334014893
After 7 epoch, w is 0.0066329240798950195, loss is 1.583296537399292
After 8 epoch, w is -0.1946936696767807, loss is 1.0133098363876343
After 9 epoch, w is -0.35575494170188904, loss is 0.6485182642936707
After 10 epoch, w is -0.4846039414405823, loss is 0.41505166888237
After 11 epoch, w is -0.5876831412315369, loss is 0.26563310623168945
After 12 epoch, w is -0.6701465249061584, loss is 0.1700051873922348
After 13 epoch, w is -0.7361172437667847, loss is 0.10880331695079803
After 14 epoch, w is -0.7888938188552856, loss is 0.0696341097354888