In [1]:
import tensorflow as tf

In [2]:
import numpy as np

## 1 常用函数

**理解 axis**

在一个二维张量或数组中，可以通过调整 axis 等有 0 或 1 控制执行维度
 + `axis=0` 代表跨行（经度，down）
 + `axis=1` 代表跨列（维度，across）
 
如果不指定 axis ，则所有元素参与计算。

&nbsp; | col0 | col1 | col2 | ...
-------|------|------|------|----
 **row0** |  ╬|════|═══▶| axis=1
 **row1** |  ║| 
 **row2** |  ▼|
 **...**  |  axis=0 |

In [3]:
x = tf.constant([[1, 2, 3], [2, 3, 4]], dtype=tf.float32)
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [2., 3., 4.]], dtype=float32)>

### 1.1 强制 tensor 转换为该数据类型

`tf.cast(张量名,dtype=数据类型)`

In [4]:
tf.cast(x, tf.int32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4]])>

### 1.2 计算张量维度上元素的最小值

`tf.reduce_min(张量名)`

In [5]:
tf.reduce_min(x)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [6]:
tf.reduce_min(x, axis=0)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [7]:
tf.reduce_min(x, axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

### 1.5 计算张量沿着指定维度的和

`tf.reduce_sum(张量名, axis=操作轴)`

In [8]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=15.0>

In [9]:
tf.reduce_sum(x, axis=0)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([3., 5., 7.], dtype=float32)>

In [10]:
tf.reduce_sum(x, axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([6., 9.], dtype=float32)>

### 1.6 tf.Variable

`tf.Variable(初始值)` 将变量标记为“**可训练**”，被标记的变量会在反向传播中记录梯度信息。神经网络训练中，常用该函数标记待训练参数。

In [11]:
tf.Variable(tf.random.normal([2, 2], mean=0, stddev=1))

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.9839119 , -0.4866405 ],
       [ 0.8357658 , -0.18603233]], dtype=float32)>

### 1.7 TensorFlow 中的数学运算

 + **对应元素**的四则运算：`tf.add`、`tf.asubtract`、`tf.multiply`、`tf.divide`
 + 平方、次方、开方：`tf.squre`、`tf.pow`、`tf.sqrt`
 + 矩阵乘：`tf.matmul`
 
**注** 只有维度相同的张量才可以做四则运算

In [12]:
a = tf.ones([1, 3])
a

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 1., 1.]], dtype=float32)>

In [13]:
b = tf.fill([1, 3], 3.0) # 注意值为 3.0 (或者 3.) 而非 3 , 要与 a 的数据类型一致（同为 float） 才可以进行对应元素的运算
b

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[3., 3., 3.]], dtype=float32)>

In [14]:
tf.add(a, b)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[4., 4., 4.]], dtype=float32)>

In [15]:
tf.subtract(a, b)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-2., -2., -2.]], dtype=float32)>

In [16]:
tf.multiply(a, b)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[3., 3., 3.]], dtype=float32)>

In [17]:
tf.divide(a, b)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.33333334, 0.33333334, 0.33333334]], dtype=float32)>

In [18]:
tf.pow(b, 3)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[27., 27., 27.]], dtype=float32)>

In [19]:
tf.square(b)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[9., 9., 9.]], dtype=float32)>

In [20]:
tf.sqrt(b)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1.7320508, 1.7320508, 1.7320508]], dtype=float32)>

In [21]:
c = tf.ones([3, 2])
d = tf.fill([2, 3], 3.)
tf.matmul(c, d)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]], dtype=float32)>

### 1.8 将特征与输入进行配对

神经网络在训练时，是把输入特征和标签配对后喂入网络的。TensorFlow 给出了把特征和标签配对的函数 `tf.data.Dataset.from_tensor_slices`，其作用是切分传入张量的第一维度，生成输入特征/标签对，构建数据集。Numpy 和 Tensor 格式都可用该语句读入数据。

`tf.data.Dataset.from_tensor_slices((输入特征, 标签))`

In [22]:
features = tf.constant([12, 23, 10, 17])
labels = tf.constant([0, 1, 1, 0])
dataset = tf.data.Dataset.from_tensor_slices((features, labels))
dataset

<TensorSliceDataset shapes: ((), ()), types: (tf.int32, tf.int32)>

In [23]:
for elem in dataset:
    print(elem)

(<tf.Tensor: shape=(), dtype=int32, numpy=12>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(), dtype=int32, numpy=23>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=10>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=17>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)


### 1.9 对某给函数的指定参数进行求导运算

可以在 with 结构中，使用 `tf.GradientTape` 实现某个函数对指定参数的求导运算。

with 结构记录计算过程，`tape.gradient` 求出张量的梯度
```python
with tf.GradientTape() as tape:
    若干计算过程
grad = tape.gradient(函数, 要求导的参数)
```

In [24]:
# 求 x^2  在 3.0 处的导数
with tf.GradientTape() as tape:
    x = tf.Variable(tf.constant(3.0))
    loss = tf.pow(x, 2)
grad = tape.gradient(loss, x)
grad

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

### 1.10 独热编码

独热编码（one-hot encoding）：在分类问题中，常用独热编码做标签。

标记类别：1 表示是，0 表示非

举例来说，有标签 `(0狗尾草鸢尾, 1杂色鸢尾, 2弗吉尼亚鸢尾)` ,其正确结果为 1，那么独热码的表示则为 `(0, 1, 0)`

`tf.one_hot` 函数将待转换数据，转换为 one-hot 形式的数据输出

`tf.one_hot(待转换数据, depth=几分类)`

In [25]:
# 标签类别为 3 个，最小为 0，最大为 2
classes = 3
labels = tf.constant([1, 0, 2])
output = tf.one_hot(labels, depth=classes)
output

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]], dtype=float32)>

### 1.11 tf.nn.softmax

当 n 分类的 n 个输出 `(y0, y1, ... ,yn-1)` 通过 softmax 函数便符合概率分布了。
$$\forall{x} P(X=x)\in [0,1] and \sum_{x}P(X=x)=1$$

Softmax 函数公式如下
$$Softmax(y_i) = \frac{e^{y_i}}{\sum_{j=0}^{n}e^{y_j}}$$

In [26]:
y = tf.constant([1.01, 2.01, -0.66])
tf.nn.softmax(y)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.25598174, 0.69583046, 0.04818781], dtype=float32)>

### 1.12 参数自减 assign_sub

赋值操作，更新参数的值并返回。调用 assign_sub 前，先用 tf.Variable 定义变量为可训练（可自更新）。

`x.assign_sub(x要自减的内容)`

同理还有参数自增，`x.assign_add(x要自增的内容)`

In [27]:
x = tf.Variable(4)
x.assign_sub(1) # x -= 1

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=3>

### 1.13 返回指定维度最大索引

返回张量沿指定维度**最大值的索引** `tf.argmax(张量名, axis=操作轴)`

In [28]:
test = np.array([[1, 2, 3], [2, 3, 4], [5, 4, 3], [8, 7, 2]])
test

array([[1, 2, 3],
       [2, 3, 4],
       [5, 4, 3],
       [8, 7, 2]])

In [29]:
tf.argmax(test, axis=0)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([3, 3, 1], dtype=int64)>

In [30]:
tf.argmax(test, axis=1)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([2, 2, 0, 0], dtype=int64)>